version: '3.9'
services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "P@ssw0rd"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"

# webapi:
#   build:
#     context: .
#     dockerfile: Dockerfile
#   ports:
#     - '5000:80'
#   depends_on:
#     - db

# db:
#   image: postgres
#   restart: always
#   ports:
#     - '5432:5432'
#   environment:
#     POSTGRES_USER: admin
#     POSTGRES_PASSWORD: admin1234
#     POSTGRES_DB: Restful
#   volumes:
#     - .dbdata:/var/lib/postgresql/data
